import { SCREEN_WIDTH, SCREEN_HEIGHT } from './metrics';


export const BASE_PADDING = 16;

// CARD
export const BASE_CARD_WIDTH = SCREEN_WIDTH - BASE_PADDING;
export const BASE_CARD_USER_IMAGE_SIZE = SCREEN_WIDTH * 0.11;
export const BASE_CARD_IMAGE_OPTIONS_WIDTH = SCREEN_WIDTH * 0.288;
export const BASE_CARD_IMAGE_OPTIONS_HEIGHT = BASE_CARD_IMAGE_OPTIONS_WIDTH * 1.192;
export const BASE_CARD_TEXT_OPTIONS_HEIGHT = SCREEN_WIDTH * 0.11;
export const BASE_CARD_IMAGE_TEXT_OPTIONS_HEIGHT = SCREEN_WIDTH * 0.15;
export const BASE_CARD_IMAGE_TEXT_IMAGE_SIZE = SCREEN_WIDTH * 0.11;

// BUTTON
export const BUTTON_WIDTH = SCREEN_WIDTH * 0.29;
export const BUTTON_HEIGHT = BUTTON_WIDTH * 0.35;

// HEADER
export const HEADER_WIDTH = SCREEN_WIDTH;
export const HEADER_HEIGHT = SCREEN_HEIGHT * 0.125;

// SEARCH AUTOCOMPLETE
export const AUTOCOMPLETE_WIDTH = SCREEN_WIDTH - BASE_PADDING;
export const AUTOCOMPLETE_HEIGHT = 56;
export const AUTOCOMPLETE_RESULTS_HEIGHT = SCREEN_HEIGHT * 0.4;

// HASHTAGS CARD
export const HASHTAG_CARD_WIDTH = SCREEN_WIDTH - BASE_PADDING;
export const HASHTAG_CARD_HEIGHT = HASHTAG_CARD_WIDTH * 0.2;
export const HASHTAG_CARD_BUTTON_WIDTH = SCREEN_WIDTH * 0.3;

// ANSWER SCREEN
export const ANSWER_USER_IMAGE_SIZE = SCREEN_WIDTH * 0.177;
export const ANSWER_SWIPE_OPTION_WIDTH = SCREEN_WIDTH - BASE_PADDING;
export const ANSWER_SWIPE_OPTION_HEIGHT = ANSWER_SWIPE_OPTION_WIDTH * 1.1;
export const ANSWER_SWIPE_OPTION_IMAGE_WIDTH = SCREEN_WIDTH * 0.86;
export const ANSWER_SWIPE_OPTION_IMAGE_HEIGHT = ANSWER_SWIPE_OPTION_IMAGE_WIDTH * 1.1;
export const ANSWER_SWIPE_OPTION_TEXT_IMAGE_WIDTH = SCREEN_WIDTH * 0.6;
export const ANSWER_SWIPE_OPTION_TEXT_IMAGE_HEIGHT = ANSWER_SWIPE_OPTION_TEXT_IMAGE_WIDTH;
export const ANSWER_SWIPE_MOVE_BUTTONS_SIZE = 48;

// RESULT
export const RESULT_CARD_WIDTH = SCREEN_WIDTH - BASE_PADDING;
export const RESULT_CARD_HEIGHT = RESULT_CARD_WIDTH * 0.255;
export const RESULT_CARD_IMAGE_SIZE = SCREEN_WIDTH * 0.177;
export const VOTES_MODAL_WIDTH = SCREEN_WIDTH - 2 * BASE_PADDING;
export const VOTES_MODAL_HEIGHT = VOTES_MODAL_WIDTH * 1.54;
export const VOTES_MODAL_USER_IMAGE_SIZE = SCREEN_WIDTH * 0.11;


// SEND SCREEN
export const SEND_SCREEN_BUTTON_OPTIONS_WIDTH = SCREEN_WIDTH * 0.3;
export const SEND_SCREEN_BUTTON_SEND_WIDTH = SCREEN_WIDTH * 0.444;
export const SEND_SCREEN_ICONS_SIZE = 24;


// LOGIN SCREEN
export const LOGIN_SCREEN_BUTTON_WIDTH = SCREEN_WIDTH * 0.4 - BASE_PADDING / 2;
